---
title: "New Analysis"
author: "WAK"
date: "today"
format:
  html: 
    toc: true
    toc-location: left
editor: visual
---

```{r}
#| echo: false
#| include: false
#| warning: false

library(epiDisplay)
library(knitr)
library(pROC)
library(tidyverse)
library(readxl)
library(ggplot2)
library(gmodels)
library(ggbeeswarm)
library(dplyr)
library(ggpubr)
library(psych)
library(lme4)
library(Matrix)
library(lmerTest)
library(irr)
library(lmerTest)
library(emmeans)
library(doBy)       
library(gmodels)    
library(car)           
library(cowplot)       
library(gridGraphics)  
library(multcomp)
library (broom)
library(DT)
library(gt)
```

```{r}
#| echo: false
#| include: false
#| warning: false
#| 
#import the data

treatment <- read_csv ("data/ENROLL FINAL 04062022.csv")

#create data set ("new") excluding all exclusions 

new <- treatment |> 
  filter (ExYN10 == 0)


wths <- read_csv ("data/Weight HS Final 04072022.csv")
wths$week <- as.factor(wths$week)


```

## New Analysis for Disbudding Y2

This analysis is a new one for the disbudding Y2 data collected during summer of 2021. We enrolled 560 goat kids in a disbudding trial to investigate the effect of multi-modal pain management vs. a positive control.

## Descriptive Table of Enrolled Goat Kids

```{r}
#| echo: false


table1 <- new |> 
  group_by(Treatment) |> 
  summarize(
    avgbwt = round(mean(bwtkg, na.rm = TRUE), 2),
    sdbwt = round(sd(bwtkg, na.rm = TRUE), 2), 
    avgdia = round(mean(DIAenroll, na.rm = TRUE), 2),
    sddia = round(sd(DIAenroll, na.rm = TRUE), 2),
    avgewt = round(mean(weight, na.rm = TRUE), 2), 
    sdewt = round(sd(weight, na.rm = TRUE), 2)
  ) |> 
  ungroup()
  
gt(table1) 

new |> 
  group_by (Treatment, Sex) |> 
  count() |> 
  ungroup()

CrossTable(new$Treatment,  new$Sex, prop.r=FALSE, prop.c = FALSE, fisher=TRUE)


new |> 
  group_by(Treatment, Breed) |> 
  count() |> 
  ungroup()

CrossTable(new$Treatment,  new$Breed, prop.r=FALSE, prop.c = FALSE, fisher=TRUE)


t.test(new$weight~new$Treatment)
shapiro.test(new$weight)

new |> 
  ggplot (mapping = aes(x=weight))+
          geom_histogram()
        


t.test(new$DIAenroll~new$Treatment)
shapiro.test(new$DIAenroll)

new |> 
  ggplot (mapping = aes(x=DIAenroll))+
          geom_histogram()
        

  
  

```

## More enrollment and day of disbudding

```{r}
#| echo: false
#| warning: false

wths |> 
  group_by(Treatment, week) |> 
  summarize(
    wt = round(mean(weight, na.rm = TRUE), 2),
    sdwt = round(sd(weight, na.rm = TRUE), 2), 
  ) |> 
  ungroup()

week0 <- wths |> 
  filter (week == 0) 

t.test(week0$weight~week0$Treatment)


```
